apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - secret-store.yaml
  - external-secret.yaml
  - docker-registry-secret.yaml
  - deployment.yaml
  - image-automation.yaml
